version: "3"

services:
  ta-postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=log
    volumes:
      -
  migratiom:
    image: migrate/migrate
    volumes:
      - .:/migrations
    command:
      -
  ta-backend:
    build: ./main
    ports:
      - 8080:8080
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_HOST=todo-postgres
      - DB_PORT=5432
      - DB_DATABASE=log
    depends_on:
      - todo-postgres